### ISSUE TITLE
Can we use the dll that makefile produces?

### ISSUE THREAD

**Issue by Scratch-net** [alipha/csharp-argon2#1]
Hi! 
I know that you use proxy files for exporting Argon2 functions but argon2 does already produce mingw DLL by itself. Is is possible to use it without proxy like jvm binding does? 

I would like to make an argon2 nuget package but unsure if it's possible to use argon2's dll

**Comment by alipha** [comment]
@Scratch-net 
I would think you'd be able to call the mingw libargon2.dll directly from the C#--just rename the crypto_argon2_\* references in PasswordHasher.cs to argon2_*. I just felt it made more sense to build everything within Visual Studio.

I started working on a nuget package. My first attempt you can actually download off of nuget right now; however, I have some work to do for it still. Right now I have a couple issues--I need to target both x64 and "Any Cpu" it seems.  I also need to figure out how to get libargon2.dll to be recognized as a dependency.  When I added my argon2 nuget package to a test project, the libargon2.dll appears in packages\Liphsoft.Crypto.Argon2.1.0.0\lib\libargon2.dll fine, but then Visual Studio doesn't know to copy it into the bin\ directory when it builds my test project.

If you know a lot about nuget packages and can help me with either of my issues, that'd be appreciated.  Otherwise, I'm going to look at it more tomorrow.

**Comment by Scratch-net** [comment]
Hi!
I tried to replace crypto_argon2_\* with argon2_\* but it did not work. Maybe because of size_t and stuff like that.

As for the copying native dll to "bin" directory, you need to do 2 things
1) Patch the csproj to add your specific .targets
2) In your .target file you do the copying dependent on the architecture x86/x64

A good example is Cefsharp library, It does exactly that.

An example of ".targets" file which cefsharp uses to copy native webP library to bin folder:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="PlatformCheck" BeforeTargets="ResolveAssemblyReferences" Condition="(('$(Platform)' != 'x86') AND ('$(Platform)' != 'x64'))">
    <Error Text="$(MSBuildThisFileName) does not work correctly on '$(Platform)' platform. You need to specify platform (x86 / x64)." />
  </Target>

  <Target Name="CefSharpCommonCopyBinaries" BeforeTargets="AfterBuild">
    <ItemGroup>
      <CefSharpBinaries Include="$(MSBuildThisFileDirectory)..\CefSharp\$(Platform)\*.*" />
    </ItemGroup>
    <Message Importance="high" Text="-- CefSharp.Common.targets: Copying files from $(MSBuildThisFileDirectory)..\CefSharp\$(Platform) to $(TargetDir)" />
    <Copy SourceFiles="@(CefSharpBinaries)" DestinationFolder="$(TargetDir)" />
  </Target>
</Project>
```

An instruction on how to add .targets and .props to project can be found here:
https://docs.nuget.org/create/creating-and-publishing-a-package#import-msbuild-targets-and-props-files-into-project

looks like all you need is \build folder

Let me know if I can help with anything else

**Comment by danielmendez88** [comment]
How can I use the libargon2.dll ??? I have problems with this, if you can explain me, I gonna thank you

**Comment by alipha** [comment]
@danielmendez88 Build your application and the csharp-argon2 library as x64 because libargon2.dll (at https://github.com/alipha/csharp-argon2/blob/master/csharp-argon2/libargon2.dll ) is a 64-bit DLL. If you need a 32-bit DLL, at this point, you'll have to build the libargon2 project using VC++. I hope to have a 32-bit copy of the DLL people to use soon so they don't have to build libargon2 by hand.

Then make sure that Liphsoft.Crypto.Argon2.dll and libargon2.dll are findable by your application by making sure they're both in the same directory as your executable or otherwise in the one of the locations specified  by your PATH environment variable.

**Comment by alipha** [comment]
@danielmendez88 @Scratch-net
Sorry for taking so long to finally do this correctly, but I created a nuget package that should "just work". If you search for argon2 in the nuget package manager, mine should be the only one that comes up (for now). 

Version 1.0.3 of Liphsoft.Crypto.Argon2 will work for x86 or x64 platforms (if your configuration is "Any CPU", it assumes that's x86, which I realize may not be always accurate) and copy the appropriate dlls to the correct place when it builds. Let me know if you run into any issues and hopefully I'll have a shorter turnaround time.

**Comment by Scratch-net** [comment]
Thank you so much!

**Comment by danielmendez88** [comment]
thanks a lot!!
