### ISSUE TITLE
Exception when trying to verify a hash

### ISSUE THREAD

**Issue by silkfire** [alipha/csharp-argon2#3]
I'm trying to verify a hash but on doing that get an exception from the library. The error is not particularly descriptive: it just says "-35 (35)". What does this mean? 

Also, I'm wondering, if you setup your hasher with one set of variables, are you only able to verify hashes that honor these variables or does it not matter? If so, maybe the verify method should be made static?

**Comment by alipha** [comment]
@silkfire 

Turns out that the latest version of the argon2 C library changed the error codes and I did not notice.  -35 means that the verification failed (VERIFY_MISMATCH).  PasswordHasher.Verify is supposed to return false if the password does not match the hash, not throw an exception.  I corrected this problem and so now Verify will return false if the hash doesn't match.

I updated the repo with the fix and I just pushed Liphsoft.Crypto.Argon2 version 1.0.4 to nuget.  Thanks for bringing this to my attention.

Currently PasswordHasher.Verify is not static because of one thing: I need to know whether to call the C library verify function with an type of Argon2d or Argon2i and so I look at the PasswordHasher object for that.  Really, I could just parse the encoded hash to determine whether it's Argon2d or Argon2i, which yes, I may update the code to do that in a future version and make Verify static.

**Comment by silkfire** [comment]
@alipha Thank you so much for fixing this. The workaround was easy: I enclosed the statement in a try catch clause with an initial boolean variable and it worked just as intended. 

Okay, your reasoning sounds pretty legit. It's nothing important at the moment as it doesn't deter from the initial functionality but I guess it's more effective memory wise because you don't have to setup the hasher object of you're doing things in a loop.
