### ISSUE TITLE
Why not compare two Argon hashes directly?

### ISSUE THREAD

**Issue by BlueRaja** [alipha/csharp-argon2#6]
The XML docs say

> Do not compare two Argon2 hashes directly. Instead, use the Verify or VerifyAndUpdate methods.

Why?  Does hashing the same password with the same parameters not always result in the same hash?  if not, how is Argon supposed to be used as [a replacement for PBKDF2](https://en.wikipedia.org/wiki/PBKDF2#Alternatives_to_PBKDF2)?

**Comment by alipha** [comment]
You should never use == or compareTo on secret data because of timing attacks--the strings "aaaaaaaa" and "zaaaaaaa" will take less time to compare than "aaaaaaaa" and "aaaaaaaz". You can use this information to recover the secret.  Cryptographic libraries come (or, at least, should come) with a "safe comparison" method which takes the same amount of time regardless of whether the first characters are different or the last characters.

Secondly, yes, `string Hash(string password)` and `string Hash(byte[] password)` will generate a random salt each time and therefore they WILL produce different hashes each time. If you're using Argon2 for password storage **this is what you want** because then attackers won't be able to tell if two people have the same password.  So yes, this also means that you need to use the `Verify` or `VerifyAndUpdate` methods so that the same salt will be used so that it will generate the same hash when attempting to verify.  

There is no reason I can think of that you would want to use the `string Hash(string password, string salt)` and `string Hash(byte[] password, byte[] salt)` but I provided them for completeness. If you want to use Argon2 as a replacement for PBKDF2 (that is, as a key derivation function), then you should use the `byte[] HashRaw(string password, string salt)` or `byte[] HashRaw(byte[] password, byte[] salt)` methods. In which case, there's no reason you would need to compare the byte[] keys it generates.

**Comment by BlueRaja** [comment]
So wait, the string returned by `Hash()` isn't just the hex-string of the hash?  It has some sort of format _(it would have to, in order for `Verify` to know the salt)_?  Is that format documented anywhere?

**Comment by alipha** [comment]
Yes, the hash is encoded such that it contains everything you need to recreate the hash, minus the password. I don't seem to have it documented anywhere, but here's the code to format the encoded hash: https://github.com/alipha/csharp-argon2/blob/master/csharp-argon2/HashMetadata.cs#L80

The original Argon2 project (https://github.com/P-H-C/phc-winner-argon2 ) contains an example:

$argon2i$v=19$m=65536,t=2,p=4$c29tZXNhbHQ$RdescudvJCsgt3ub+b+dWRWJTmaaJObG
